config/routes.rb
Rails.application.routes.draw do
  get "accounts/index"
  get "accounts/show"
  get "accounts/edit"
  get "accounts/new"
  get "accounts/create"
  get "accounts/update"
  get "accounts/destroy"
  get "commodity_categories/index"
  # root to: 'admin/top#index'
  root to: "top#index"

  # get "login" => "sessions#new", as: :login
  # post "session" => "sessions#create", as: :session
  # delete "session" => "sessions#destroy"

  # get 'login', to: 'sessions#new', as: :login
  # post 'session', to: 'sessions#create', as: :session
  # delete 'session', to: 'sessions#destroy'

  scope controller: :sessions do
    get "login", action: :new, as: :login
    # post 'session', action: :create, as: :session
    # delete 'session', action: :destroy
    # - 20231014 第一引数が urlにあたる
    resource :session, only: [:create, :destroy]
  end

  #^ 青木 ★要更新 - 20231014 /appointments/new => /apo/new  のように変更可能!
  resources :appointments, path: "appointments" do
    collection do
      get :search
    end
  end

  # ¥ 単一継承でも下記のように記載する必要あり
  resources :smm_appointments # This will generate smm_appointments_path among others
  resources :cx_appointments # This will generate cmm_appointments_path among others

  #^ 青木 ★要更新 - 20231014 /appointments/new => /apo/new  のように変更可能!
  resources :service_categories, path: "service_categories"

  resources :commodity_categories, path: "commodity_categories"

  resources :accounts, path: "accounts" do
    member do
      get "change_password", to: "accounts#change_password" # for displaying the password change form
      patch "update_password"  # for submitting the password change form
    end
  end

  # 検証用
  get "html/scroll_x"

  # # - 20231013 上記の書き換え 厳密には Prefix と URI-Patternが変わる
  # * Prefix: login => login_session   |   Uri-Pattern: /login  =>   /session/login
  # resource :session, only: [:new, :create, :destroy], controller: :sessions do
  #   get 'login', action: :new, as: :login
  # end

  # root "top#index"
  # get 'top/index', to: 'top#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  namespace :admin do
    root "top#index"
  end

  namespace :user do
    root "top#index"
  end
end

# - 20231013 - ルーティングに名前を与えるメリット:
# * シンボルでURLパスを表現することには、主に2つのメリットがあります。1つは、プログラマが名前を書き間違えたときにエラーになることです。たとえば、URLパスを文字列で指定した場合"/stuff/login" と書き間違えても、Railsはエラーを出しません。私たちが実際にリンクをクリックし「404 Not Found」のページを見て、はじめてミスに気づくことになります。しかし、URLパスにシンボル:stuff_login を指定した場合は、リンク元のページを表示しただけでエラーが発生します。間違いはなるべく早く発見されるべきですので、これは大きな利点です。

# ¥ 名前を与えることで login_path / login_url といったヘルパーメソッドが定義される
# ¥ => ヘルパーメソッドを用いるとurlにクエリパラメータを付与できる
# * 前者はURLのパス部分を返し、後者はURL全体を返します。　ヘルパーメソッド login_path を用いれば、次のようにしてERBテンプレートにリンクを埋め込むことができます。
# - <%= link_to "ログイン", login_path %>
# login_path の部分は:login とも書けるのでヘルパーメソッドの出番はなさそうにも思えますが、ヘルパーメソッドを用いるとURLにクエリパラメータを付加することが可能になります。
# - <%= link_to "ログイン", login_path(tracking: "001") %>
# この場合、次のようなHTMLコードが生成されます。
# - <a href="/login?tracking=001">ログイン</a>

app/models/service_category.rb
class ServiceCategory < ApplicationRecord
  include StringNormalizer

  has_many :appointments

  attr_accessor :original_name

  # ¥ if @commodity_category.saveのタイミングで before_validationが起こる
  #  *  @commodity_category = CommodityCategory.new(commodity_categories_params)
  # * if @commodity_category.save
  before_validation do
    # * 引数の name は、現在のCommodityCategoryのインスタンスのname属性を指し、通常はデータベースのcommodity_categoriesテーブルのnameというカラムに対応する。
    # Store the original name before normalizing
    self.original_name = name
    # Normalize the name
    self.name = normalize_as_name(name)
    # ! # Normalize the 価格 rails7になったからか全角数字を半角に勝手に変更してくれている
    # self.price = normalize_zenkaku_number_to_number(price)
    # # Normalize the 初期費用
    # self.initial_cost = normalize_zenkaku_number_to_number(initial_cost)
  end

  # 余分な空白があった場合、取り除き、取り除いた旨のエラーメッセージを表示させる
  validate_without_extra_spaces(:original_name, :name)

  # 商材名: 必須
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  # 文字制限 type text でない限り VARCHAR(255)
  validates_length_of :name, maximum: 255, message: "が長すぎます。255文字以内にしてください"

  # 正の整数限定 sqlの型が integer の場合の最大値は 2,147,483,647
  # ! This validation declaration is evaluated in the class contextのため、format_with_delimiterは
  # ! module ClassMethodsの中に記述する必要あり　 - クラスレベルで呼び出す必要があるため
  validates :price, :initial_cost, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: INTEGER_MAX_VALUE, # Maximum value for a 4-byte signed integer
    message: "には#{format_with_delimiter(INTEGER_MAX_VALUE)}を上限とした正の整数を入力してください"
  }

  # - ransackを使用するため検索に使用する属性を定義する必要あり
  def self.ransackable_attributes(auth_object = nil)
    %w(id name description price initial_cost img_url created_at updated_at)
  end

  def self.ransackable_associations(auth_object = nil)
    %w(appointments)
  end
end

app/controllers/service_categories_controller.rb
# class ServiceCategoriesController < ApplicationController
class ServiceCategoriesController < Base
  # def index
  #   @service_categories = ServiceCategory.all
  # end

  # GET /service_categories
  def index
    # @service_categories = ServiceCategory.all
    # - service_categoriesに対してページネートできるようにする
    # @service_categories = ServiceCategory.page(params[:page])

    # `ServiceCategory.ransack`でServiceCategoryに対してransackを使う
    # params[:q]には検索フォームで指定した検索条件が入る
    @search = ServiceCategory.ransack(params[:q])

    # デフォルトのソートをid降順にする
    @search.sorts = 'id desc' if @search.sorts.empty?

    # `@search.result`で検索結果となる@service_categoriesを取得する
    # 検索結果に対してはkaminariのpageメソッドをチェーンできる
    @service_categories = @search.result.page(params[:page]).per(params[:per_page] || Kaminari.config.default_per_page)
  end

  # GET /service_category/1
  def show
    # ! @cat がここにはないが、before_action :set_cat, only: %i[ show edit update destroy ] で設定されているため使うことができる
    @service_category = ServiceCategory.find(params[:id])
    puts("show: @service_category::: #{@service_category}")
  end

  def new
    return unless current_account

    # @form = CommodityCategories::CreateForm.new
    @service_category = ServiceCategory.new
    render action: 'new'
  end

  def edit
    @service_category = ServiceCategory.find(params[:id])
  end

  def create
    # . @form = CommodityCategories::CreateForm.new(params[:name])
    # . @form = CommodityCategories::CreateForm.new(service_categories_params)
    #   # - CommodityCategories::CreateForm class自体は .save メソッドを持たないため、create_form.rbで saveと同じロジックを自作する必要あり
    # if @form.form_save
    @service_category = ServiceCategory.new(service_categories_params)
    if @service_category.save
      # flash[:success] = "CommodityCategories successfully created"
      flash.now.notice = 'CommodityCategories successfully created'
      # redirect_to "/service_categories"
      # ^ 青木 ★要更新 - 20231018
      # respond_to do |format|
      #   format.turbo_stream
      #   format.html { redirect_to "/service_categories" }
      # end
      # - フォームがTurboを使用するように設定され、アクション内で応答フォーマットまたはリダイレクトを指定しない場合、Turboのデフォルトの動作はTurbo Stream応答を探すことです。見つからない場合は、次の論理ビューに対応するHTMLレスポンスを期待します。createアクションのコンテキストでは、これは通常、新しく作成されたリソースのshowビューを意味します。
    else
      flash.now.alert = 'Something went wrong(create)'
      render 'new', status: :unprocessable_entity
    end
  end

  # ¥ 後で対応
  def update
    @service_category = ServiceCategory.find(params[:id])
    if @service_category.update(service_categories_params)
      puts("update: @service_category::: #{@service_category}")

      # render action: 'show'
      flash.now.notice = 'ServiceCategory was successfully updated'
      # redirect_to @service_category
    else
      flash.now.alert = 'Something went wrong(update)'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @service_category = ServiceCategory.find(params[:id])
    puts("params[:id];;;; #{params[:id]}")
    if @service_category.destroy
      flash.now.notice = 'Object was successfully deleted.'
      # redirect_to service_cateogrys_url
    else
      flash.now.alert = 'Something went wrong(destroy)'
      render :show, status: :unprocessable_entity
    end
  end

  private def service_categories_params
    # - <input type="text" name="login_form[email]" id="login_form_email">
    # params.require(:service_categories_create_form).permit(:name)
    # - form_withが作る キーを 下記に入力する
    # * 例:Parameters: {"service_category"=>{"name"=>"abc"}, "commit"=>"登録"}
    params.require(:service_category).permit(:name, :description, :price, :initial_cost, :img_url)
  end
end

app/helpers/service_categories_helper.rb
module ServiceCategoriesHelper
end

app/views/service_categories/_form.html.erb
<%# - 青木 要更新- 20231021 SPA %>
<%# ¥ 操作後変更したいもの - 置き換えられるもの %>
<%# * 全体を`turbo_frame_tag`で囲う %>
<%# * 編集リンクをクリックすると、_cat.html.erbの<turbo-frame>部分がこの部分に置換される %>
<%# ! 注目ポイントはturbo_frame_tagの引数にservice_categoryを利用してる。これでshow.html.erbの<turbo-frame id="service_category_1">とedit.html.erb（内でrenderしている_form.html.erb）の<turbo-frame id="service_category_1">がマッチするようになる。つまり編集リンクをクリックすると、_service_category.html.erbの<turbo-frame id="service_category_1">部分が、_form.html.erbの<turbo-frame id="service_category_1">部分に置換されるようになるよ。 %>
<%= turbo_frame_tag @service_category do %>
  <%# - 20231022 urlを省くと、railsが自動で create と update を場合分けして urlのルートを決定してくれる %>
  <%= form_with model: @service_category do |f| %>
    <%# form_with model: @service_category, url: service_categories_path do |f|  |||| %>
    <div class="flex py-4 hover:bg-amber-50">
      <%# No. %>
      <div class="px-6 flex-none w-number_column font-normal text-gray-900">
        <%# <%= f.submit "Submit", class: "apl-btn-blue" %>
        <%# ¥ ja.ymlで 手動で文字列を設定する方法 %>
        <%# <%= f.submit t("commodity_categories.form.add_item"), class: "apl-btn-blue" %>
        <%# ¥ ja.ymlで form_with を使っていた場合に共通のテキストを使用する場合 %>
        <div class="flex flex-col">
          <%= f.submit class:
                    @service_category.new_record? ? "apl-btn-blue" : "apl-btn-orange" %>
          <%= link_to "戻る", @service_category, class: "apl-btn-gray" %>
        </div>
      </div>

      <%# サービス名 %>
      <div class=" gap-3 px-6 w-1/5 font-normal text-gray-900">
        <%# sr-only は tailwindが用意しているscreen reader用で画面には表示されない %>
        <%= f.label :name, class: "sr-only" %>
        <%= f.text_field :name, class: "w-full", placeholder: "" %>
        <%# - validationメッセージ %>
        <% if @service_category.errors[:name].present? %>
          <%= render partial: "/shared/validation_errors", locals: { object: @service_category, attribute: :name } %>
        <% end %>
      </div>

      <%# サービス詳細 %>
      <%# ! classに flex を入れると縦いっぱいに広がる %>
      <div class="px-6 grow">
        <%# sr-only は tailwindが用意しているscreen reader用で画面には表示されない %>
        <%= f.label :description, class: "sr-only" %>
        <%= f.text_area :description, class: "w-full", placeholder: "" %>
      </div>

      <%# 価格 %>
      <div class="px-6 w-1/5">
        <%# sr-only は tailwindが用意しているscreen reader用で画面には表示されない %>
        <%= f.label :price, class: "sr-only" %>
        <%= f.text_field :price, class: "w-full", placeholder: "" %>
        <%# - validationメッセージ %>
        <% if @service_category.errors[:price].present? %>
          <%= render partial: "/shared/validation_errors", locals: { object: @service_category, attribute: :price } %>
        <% end %>
      </div>

      <%# 初期費用 %>
      <div class="px-6 w-1/5">
        <div class="flex gap-2">
          <%# sr-only は tailwindが用意しているscreen reader用で画面には表示されない %>
          <%= f.label :initial_cost, class: "sr-only" %>
          <%= f.text_field :initial_cost, class: "w-full", placeholder: "" %>
          <%# - validationメッセージ %>
          <% if @service_category.errors[:initial_cost].present? %>
            <%= render partial: "/shared/validation_errors", locals: { object: @service_category, attribute: :initial_cost } %>
          <% end %>
        </div>
      </div>

      <%# edit / delete %>
      <div class="flex flex-col px-6 w-two_icons">
        <%= f.submit class:
                  @service_category.new_record? ? "apl-btn-blue" : "apl-btn-orange" %>
        <%= link_to "戻る", @service_category, class: "apl-btn-gray" %>
      </div>
    </div>
    <!--  <div class="flex py-4 hover:bg-amber-50">  -->
    <!-- Add a Submit button -->
  <% end %>
<% end %>
<%# //////////////////////////////// %>

app/views/service_categories/_service_category.html.erb
<%# - 青木 要更新- 20231015 SPA %>
<%# ¥ 操作後変更したいもの - 置き換えられるもの %>
<%= turbo_frame_tag service_category do %>
  <%# <div class="flex hover:bg-gray-50"> %>
  <%# ¥ turbo_streamを使うかどうかによってアイテムの番号を変化させる %>
  <%# ! _counterは 呼び出し元が render @service_categories などの collection時のみ使える %>
  <%# ! turbo_stream.prepend "service_categories" では collectionとならないため使えないため条件分岐が必要 %>
  <%# - Determine the value of num_counter based on various conditions %>
  <% if defined?(service_category_counter) && service_category_counter %>
  <!-- Turbo stream specific rendering logic -->
    <% num_counter = service_category_counter + 1 %>
  <% elsif local_assigns[:within_turbo_stream_create] %>
  <!-- Turbo stream specific rendering logic -->
    <% num_counter = "登録完了" %>
  <% elsif local_assigns[:within_turbo_stream_update] %>
  <!-- Turbo stream specific rendering logic -->
    <% num_counter = "更新完了" %>
  <% elsif local_assigns[:go_back] %>
    <% num_counter = "編集中止" %>
  <% else %>
    <!-- Your original rendering logic -->
    <% num_counter = "unknown" %>
  <% end %>
  <%# - flex の items-stretch ※ items-centerにすると、真ん中になった要素の高さが最大の高さになり、borderがきれいにならない 途中で線が途切れる %>
  <%# ¥ 最適解: 1. 親要素をflexにする　 2. 子要素に self-center(align-self: center;)をつけることで中央揃えにできる!!  %>

  <%# ! 本要素内を変更する場合、 index.html.erbの列名部分も調整する必要あり  %>
  <div class="_service_category_container flex hover:bg-amber-50 border-r border-b border-gray-300 items-stretch">
    <%# No. %>
    <div class="px-6 py-8 justify-center w-number_column font-normal text-gray-900 border-r border-b border-gray-300">
      <div class="text-sm">
        <div class="font-medium text-gray-700 text-center"><%= num_counter %></div>
      </div>
    </div>

    <%# サービス名 %>
    <div class="flex gap-3 px-6 w-1/5 font-normal text-gray-900 border-r border-b border-gray-300  ">
      <div class="relative h-10 w-10 self-center">
        <img class="h-full w-full rounded-full object-cover object-center" src="<%= service_category.img_url || '/pics/dog_butt.jpg' %>" alt="" />
      </div>
      <div class="text-sm self-center">
        <div class="font-medium text-gray-700"><%= service_category.name %></div>
      </div>
    </div>

    <%# サービス詳細 %>
    <%# ¥ grow ではなく、 実際の幅よりも大きい w-1/3 とすることでループさせて表示させる同じ要素で文字列が少ない or  入っていないものも同じ広い横幅にすることができる %>
    <div class="flex px-6 w-1/3 border-r border-gray-300">
      <span class="inline-flex items-center gap-1 rounded-full bg-green-50 px-2 py-1 text-xs font-semibold text-green-600 self-center break-all">
        <span class="h-1.5 w-1.5 rounded-full bg-green-600"></span>
        <%= service_category.description %>
      </span>
    </div>

    <%# - 青木 要削除 - 20231028 %>
    <%# 価格 %>
    <div class="flex px-6 w-1/5 border-r border-gray-300">
      <div class="self-center">¥<%= number_with_delimiter(service_category.price) %></div>
    </div>

    <%# 初期費用 %>
    <div class="flex px-6 w-1/5 border-r border-gray-300">
      <div class="flex gap-2 self-center">
        <span class="inline-flex items-center gap-1 rounded-full bg-blue-50 px-2 py-1 text-xs font-semibold text-blue-600">
          ¥<%= number_with_delimiter(service_category.initial_cost) %>
        </span>
      </div>
    </div>

    <div class="flex px-6 w-two_icons">
      <div class="flex justify-end gap-4 self-center">
        <%# - 編集アイコン %>
        <%# ¥ mr-3を加えた %>
        <%# ブロックと一緒に使うと、ブロック内のコンテンツがリンクのコンテンツになります。この場合の第1引数はURLまたはパスヘルパーで、第2引数はHTMLオプションです： %>
        <%= link_to "/service_categories/#{service_category.id}/edit", class: "mr-3", data: { tooltip: 'Edit' }  do %>
          <%# ! NG これだと select * となり意図しない動作となった。 link_to "/service_categories/#{service_category}/edit", class: "mr-3", data: { tooltip: 'Edit' }  do %>
          <!-- contents of the link go here -->
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            class="h-6 w-6 hover:text-green-400"
            x-tooltip="tooltip"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125"
            />
          </svg>
        <% end %>

        <%# - 削除アイコン %>
        <%= button_to service_category_path(service_category), method: :delete, data: { tooltip: 'Delete', turbo_confirm: '本当に削除しますか？' } do %>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            class="h-6 w-6 hover:text-red-500"
            x-tooltip="tooltip"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0"
            />
          </svg>
        <% end %>
      </div>
    </div>
  </div><!--  <div class="flex py-4 hover:bg-amber-50">  -->
<% end %>

app/views/service_categories/create.turbo_stream.erb
<% puts("ugoiteiru??") %>

<%# - 1. 新規作成で作成で登録したときにリストの一番上にたった今登録した内容を表示させる %>
<%# - 2. 作成後、入力フォームを削除する %>
<%# `#service_categories`の先頭に登録された@service_categoryを追加する %>
<%# turbo_stream.prepend "service_categories", @service_category %>
<%# ! service_category_counter は 部分テンプレートで使えない collection: でないため %>
<%= turbo_stream.prepend "service_categories" do %>
  <%= render partial: 'service_category', locals: { service_category: @service_category, within_turbo_stream_create: true } %>
<% end %>
<%# ¥ 登録の入力フォームを空にする(下記のように要素内の中身が空になる) 結果、新規登録のフォームがなくなる %>
<%#  turbo-frame id="new_service_category" src="http://127.0.0.1:3000/service_categories/new" complete=""></turbo-frame> %>
<%= turbo_stream.update ServiceCategory.new, "" %>
<%# ¥ flashメッセージを notice か alertかを判断して turbo_streamで表示する %>
<%= render "/shared/turbo_stream_flash" %>

app/views/service_categories/destroy.turbo_stream.erb
<%# ServiceCategory詳細（`#service_category_1`となる要素）を削除する %>
<%= turbo_stream.remove @service_category %>
<%# ¥ flashメッセージを notice か alertかを判断して turbo_streamで表示する %>
<%= render "/shared/turbo_stream_flash" %>

app/views/service_categories/edit.html.erb
<%# - 編集ボタンを押すと、 %>
<%= render 'form' %>

app/views/service_categories/index.html.erb
<div>余裕があるときにアイコンをアップロードし、表示できるようにする</div>
<div><%= ServiceCategory.find(1).description %></div>
<%# - ransack用 検索機能 %>
<%# ransackを利用した検索フォームでは、form_withの代わりにsearch_form_forを使う %>
<div class="flex mx-5 items-end">
  <%= search_form_for @search, html: { class: 'flex items-end' } do |f| %>
    <div class="flex flex-col mr-2">
      <%# `カラム名_cont`とすることで、カラムに対してLIKEを使った曖昧一致検索ができる %>
      <%= f.label :name_cont, "商材名(部分)" %>
      <%= f.search_field :name_cont %>
    </div>
    <div class="flex flex-col mr-2">
      <%# `カラム名_eq`とすることで、カラムに対して完全一致検索ができる %>
      <%= f.label :name_eq, "商材名(完全)" %>
      <%= f.search_field :name_eq %>
    </div>

    <div class="">
      <%= f.submit class: "apl-btn-blue", data: { turbo_frame: "service_category_list" } %>
      <%# 検索結果と検索フォームをクリアする %>
      <%= link_to "クリア", "/service_categories", class: "apl-btn-reset" %>
    </div>
  <% end %>
  <%= form_tag(request.path, method: :get, id: 'per_page_form') do %>
    Display:
    <%= select_tag "per_page", options_for_select([3, 5, 10, 20, 30, 50], params[:per_page].to_i), onchange: "this.form.submit()" %>
    items per page
    <%= paginate @service_categories, params: { per_page: params[:per_page] } %>
  <% end %>
</div>

<%# - ransack用 END %>
<%= link_to "/service_categories/new", class: "apl-btn-green inline-block mx-5 my-2" do %>
  <!-- contents of the link go here -->
  <button class="">新規作成(normal)</button>
<% end %>
<%# ¥ 20231018 spi用のtrubo_frame使用している %>
<%# - 青木 要更新- 20231021 SPA %>
<%# ¥ 操作後変更したいもの - data: { turbo_frame: dom_id(ServiceCategory.new) } で操作後変更したい箇所を指定している %>
<%= link_to "新規作成", "/service_categories/new", class: "apl-btn-green inline-block mx-5 my-2", data: { turbo_frame: dom_id(ServiceCategory.new) } %>
<%= turbo_frame_tag "service_category_list" do %>
  <div class="overflow-hidden rounded-lg border border-gray-200 shadow-md m-5">
    <%# !!!!!!!!!!!! %>
    <div class="w-full bg-whitetext-lefttext-sm text-gray-500divide-y divide-gray-100border-t border-gray-100">
      <div class="bg-gray-50 flex py-4">
        <div class="flex-none px-6 font-medium text-blue-600 w-number_column"><%= sort_link(@search, :id, "No.", class: "text-blue-600 border-b border-blue-600") %></div>
        <div class="flex-none w-1/5 px-6 font-medium text-blue-600 "><%= sort_link(@search, :name, "サービス名", class: "text-blue-600 border-b border-blue-600") %></div>
        <div class="px-6 grow font-medium text-gray-900">サービス詳細</div>
        <div class="px-6 w-1/5 font-medium text-gray-900">価格/月</div>
        <div class="px-6 w-1/5 font-medium text-gray-900">初期費用</div>
        <div class="flex-none px-6 py-4 font-medium text-gray-900 w-two_icons"></div>
        <!-- edit delete icon -->
      </div>
      <div id="service_categories" class="divide-y divide-gray-100 border-t border-gray-100">
        <%= turbo_frame_tag "new_service_category" %>
        <%= render @service_categories %>
      </div>
    </div>
  </div>
  <%= paginate @service_categories, params: { per_page: params[:per_page] } %>
<% end %>
<%# --------------- %>
<!-- component -->
<%# - 青木 要更新- 20231015 %>
<%# https://tinyurl.com/yst2dmtx %>

app/views/service_categories/new.html.erb
<%# - 青木 要更新- 20231015 SPA %>
<%# ¥ 操作後、表示させたいもの - 置き換えるもの %>
<%
=begin %>
<%= turbo_frame_tag "new_service_category" do %>
  <%# ! scssのみ使用する %>
  <%= stylesheet_link_tag "login", media: "all", "data-turbolinks-track": "reload" %>
  <% @title = "商材カテゴリ" %>
  <%# ---------------------------------- %>
  <div class="log-form">
    <h2><%= @title %>を作成</h2>
    <%# ! data: { turbo: "false" } をつけないと redirect_toがうまく動かない spaにしない場合は falseに設定が必要! %>
    <%= form_with model: @form, url: "/service_categories" do |f| %>
      <%= f.text_field :name, placeholder: "例: アパレル", title: "name" %>
      <%= f.submit "作成", class: "btn" %>
      <%# <a class="forgot" href="#">Forgot Username?</a> %>
      <%= link_to "Back", "/service_categories", class: "forgot" %>
    <% end %>
  </div>
<% end %>
<%# ------------------------------------ %>
<%
=end %>
<%# * new.html.erb から @service_category を引き継いでいるため、わざわざ引数で新しく ervice_category: @service_category する必要なし %>
<%# - そのまま @service_categoryが使える だがわかりやすさ重視で下記のように書いても良さそう %>
<%# <%= render "form", service_category: @service_category %>
<%= render "form" %>

app/views/service_categories/show.html.erb
<%= render @service_category, go_back: true %>

app/views/service_categories/test.html.erb
<div><%= ServiceCategory.find(1).name %></div>
<div><%= ServiceCategory.find(1).description %></div>
<%# eeえええ %>

app/views/service_categories/update.turbo_stream.erb
<%# * 編集し、 更新したときの処理 %>
<%# - #service_category_1（id属性がservice_category_1の要素）を<template>...<template>のコンテンツでreplace（置換する）する、という意味になる。これはTurbo Framesで処理するのと同じような置換処理になる %>
<%= turbo_stream.replace @service_category do %>
  <%= render partial: 'service_category', locals: { service_category: @service_category, within_turbo_stream_update: true } %>
<% end %>
<%# ¥ flashメッセージを notice か alertかを判断して turbo_streamで表示する %>
<%= render "/shared/turbo_stream_flash" %>