config/routes.rb
Rails.application.routes.draw do
  get "accounts/index"
  get "accounts/show"
  get "accounts/edit"
  get "accounts/new"
  get "accounts/create"
  get "accounts/update"
  get "accounts/destroy"
  get "commodity_categories/index"
  # root to: 'admin/top#index'
  root to: "top#index"

  # get "login" => "sessions#new", as: :login
  # post "session" => "sessions#create", as: :session
  # delete "session" => "sessions#destroy"

  # get 'login', to: 'sessions#new', as: :login
  # post 'session', to: 'sessions#create', as: :session
  # delete 'session', to: 'sessions#destroy'

  scope controller: :sessions do
    get "login", action: :new, as: :login
    # post 'session', action: :create, as: :session
    # delete 'session', action: :destroy
    # - 20231014 第一引数が urlにあたる
    resource :session, only: [:create, :destroy]
  end

  #^ 青木 ★要更新 - 20231014 /appointments/new => /apo/new  のように変更可能!
  resources :appointments, path: "appointments" do
    collection do
      get :search
    end
  end

  # ¥ 単一継承でも下記のように記載する必要あり
  resources :smm_appointments # This will generate smm_appointments_path among others
  resources :cx_appointments # This will generate cmm_appointments_path among others

  #^ 青木 ★要更新 - 20231014 /appointments/new => /apo/new  のように変更可能!
  resources :service_categories, path: "service_categories"

  resources :commodity_categories, path: "commodity_categories"

  resources :accounts, path: "accounts" do
    member do
      get "change_password", to: "accounts#change_password" # for displaying the password change form
      patch "update_password"  # for submitting the password change form
    end
  end

  # 検証用
  get "html/scroll_x"

  # # - 20231013 上記の書き換え 厳密には Prefix と URI-Patternが変わる
  # * Prefix: login => login_session   |   Uri-Pattern: /login  =>   /session/login
  # resource :session, only: [:new, :create, :destroy], controller: :sessions do
  #   get 'login', action: :new, as: :login
  # end

  # root "top#index"
  # get 'top/index', to: 'top#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  namespace :admin do
    root "top#index"
  end

  namespace :user do
    root "top#index"
  end
end

# - 20231013 - ルーティングに名前を与えるメリット:
# * シンボルでURLパスを表現することには、主に2つのメリットがあります。1つは、プログラマが名前を書き間違えたときにエラーになることです。たとえば、URLパスを文字列で指定した場合"/stuff/login" と書き間違えても、Railsはエラーを出しません。私たちが実際にリンクをクリックし「404 Not Found」のページを見て、はじめてミスに気づくことになります。しかし、URLパスにシンボル:stuff_login を指定した場合は、リンク元のページを表示しただけでエラーが発生します。間違いはなるべく早く発見されるべきですので、これは大きな利点です。

# ¥ 名前を与えることで login_path / login_url といったヘルパーメソッドが定義される
# ¥ => ヘルパーメソッドを用いるとurlにクエリパラメータを付与できる
# * 前者はURLのパス部分を返し、後者はURL全体を返します。　ヘルパーメソッド login_path を用いれば、次のようにしてERBテンプレートにリンクを埋め込むことができます。
# - <%= link_to "ログイン", login_path %>
# login_path の部分は:login とも書けるのでヘルパーメソッドの出番はなさそうにも思えますが、ヘルパーメソッドを用いるとURLにクエリパラメータを付加することが可能になります。
# - <%= link_to "ログイン", login_path(tracking: "001") %>
# この場合、次のようなHTMLコードが生成されます。
# - <a href="/login?tracking=001">ログイン</a>

app/models/appointment.rb
class Appointment < ApplicationRecord
  # - STIではここで書いたものが smm_appointment.rb と cx_appointment.rbにも共有されるため
  # - 上記のファイルに下記を別々に記述する必要なし
  belongs_to :account
  belongs_to :service_category
  belongs_to :commodity_category

  # - 既定はSTI使用時に自動で typeカラムに SmmAppointmentのように保存されるが、
  # - それだと長すぎるため、下記のように条件に応じて Smm or Cx として保存されるようにした。

  def self.inheritance_column
    "type"
  end

  def self.sti_name
    case self.name
    when "SmmAppointment"
      "Smm"
    when "CxAppointment"
      "Cx"
    else
      super
    end
  end

  def self.find_sti_class(type_name)
    case type_name
    when "Smm"
      SmmAppointment
    when "Cx"
      CxAppointment
    else
      super
    end
  end


  # # - ransackを使用するため検索に使用する属性を定義する必要あり
  def self.ransackable_attributes(auth_object = nil)
    %w(id account_id service_category_id commodity_category_id duplication company_name company_tel company_url instagram_url content call_date next_call_date sent_material_date is_next_call end_date)
  end
end

app/controllers/appointments_controller.rb
# app/controllers/appointments_controller.rb
# app/controllers/appointments_controller.rb
class AppointmentsController < Base
  # before_action :set_service_category_type, only: [:index]
  # before_action :set_search_and_appointments, only: [:index]

  def index
    # ! 一つの関数にまとめる
    if params[:service_category_type] == "smm"
      @appointments = paginated_results(Appointment.where(service_category_id: 1))
    elsif params[:service_category_type] == "cx"
      @appointments = paginated_results(Appointment.where(service_category_id: 2))
    else
      @appointments = paginated_results(Appointment.all)
    end

    # Outputs the IDs of the appointments in the log/console
    # Rails.logger.info "@appointments.pluck(:id): #{@appointments.pluck(:id)}"
    # @appointments = set_search_and_appointments
    # if

    # end


  end

  # def new
  #   @appointment = SmmAppointment.new # Assuming SmmAppointment is the default
  # end

  # 通常サーチ
  def search
    # ! 一つの関数にまとめる
    if params[:service_category_type] == "smm"
      @appointments = paginated_results(Appointment.where(service_category_id: 1))
    elsif params[:service_category_type] == "cx"
      @appointments = paginated_results(Appointment.where(service_category_id: 2))
    else
      @appointments = paginated_results(Appointment.all)
    end

    if params[:company_name_partial].present?
      @appointments = @appointments.where("company_name LIKE ?", "%#{params[:company_name_partial]}%")
    end

    if params[:company_name_exact].present?
      @appointments = @appointments.where(company_name: params[:company_name_exact])
    end

    # Rest of your search logic

    render :index # or wherever you want to render the search results
  end

  private

  def set_service_category_type
    @service_category_type = params[:service_category_type].presence || "smm"
    @service_category_id = case @service_category_type
      when "smm" then 1
      when "cx" then 2
      when "all" then 3
      else 3 # Default to the base model if no valid type is given
      end
  end

  def set_search_and_appointments
    model = case @service_category_type
      when "smm" then SmmAppointment
      when "cx" then CxAppointment
      when "all" then Appointment
      else Appointment # Default to the base model if no valid type is given
      end

    @search = model.ransack(params[:q])
    set_default_sort(@search)
    appointments = @search.result(distinct: true)

    # You might need to adjust the following line if service_category_id is not a valid column
    # for SmmAppointment and CxAppointment, or handle the condition differently.
    appointments = appointments.where(service_category_id: @service_category_id) unless @service_category_type == "all"

    @appointments = paginated_results(appointments)
  end

  def set_default_sort(search)
    search.sorts = "id desc" if search.sorts.empty?
  end

  def paginated_results(appointments)
    appointments.includes(:account, :commodity_category, :service_category)
                .page(params[:page])
                .per(params[:per_page] || Kaminari.config.default_per_page)
  end

  def appointment_params
    params.require(:appointment).permit(
      :account_id, :service_category_id, :commodity_category_id, :duplication,
      :company_name, :company_tel, :company_url, :instagram_url, :content, :call_date,
      :next_call_date, :sent_material_date, :is_next_call, :end_date
    )
  end
end

#  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# # class AppointmentsController < ApplicationController
# class AppointmentsController < Base
#   def index
#     @service_category_type = params[:service_category_type].present? ? params[:service_category_type] : "smm"

#     # ! 下記のように条件分岐すると、@searchがないというエラーが出る 20231106
#     case @service_category_type
#     when "smm"
#       @search, @appointments = smm_appointments_records
#     when "cx"
#       @search, @appointments = cx_appointments_records
#     when "all"
#       @search, @appointments = all_appointments_records
#     else
#       puts("service category is not selected.")
#     end
#     # @search, @smm_appointments = smm_appointments_records
#     # @search, @cx_appointments = cx_appointments_records
#     # @appointments = Appointment.all
#     #! 条件分岐必要 一時的にall
#     # @search = Appointment.ransack(params[:q])
#     # @search, @all_appointments = all_appointments_records

#     # @appointments = @appointments
#     puts("@appointments.pluck(:id): #{@appointments.pluck(:id)}")
#   end

#   # ! 条件分岐必須
#   def new
#     @smm_appointment = SmmAppointment.new
#   end

#   private

#   def smm_appointments_records
#     search = SmmAppointment.ransack(params[:q])

#     # デフォルトのソートをid降順にする
#     search.sorts = "id desc" if search.sorts.empty?

#     # smm_appointments = search.result.page(params[:page]).per(params[:per_page] || Kaminari.config.default_per_page)

#     # - N+1問題解決 - Use .includes to load both :account and :commodity_category associations
#     smm_appointments = search.result.includes(:account, :commodity_category, :service_category).page(params[:page]).per(params[:per_page] || Kaminari.config.default_per_page)

#     return [search, smm_appointments]
#   end

#   def cx_appointments_records
#     search = CxAppointment.ransack(params[:q])

#     # デフォルトのソートをid降順にする
#     search.sorts = "id desc" if search.sorts.empty?

#     cx_appointments = search.result.includes(:account, :commodity_category, :service_category).page(params[:page]).per(params[:per_page] || Kaminari.config.default_per_page)

#     return [search, cx_appointments]
#   end

#   def all_appointments_records
#     # @appointments = Appointment.all
#     # @smm_appointments = SmmAppointment.all
#     # @cx_appointments = CxAppointment.all

#     # `ServiceCategory.ransack`でServiceCategoryに対してransackを使う
#     # params[:q]には検索フォームで指定した検索条件が入る
#     search = Appointment.ransack(params[:q])

#     # デフォルトのソートをid降順にする
#     search.sorts = "id desc" if search.sorts.empty?

#     # `@search.result`で検索結果となる@service_categoriesを取得する
#     # 検索結果に対してはkaminariのpageメソッドをチェーンできる
#     all_appointments = search.result.includes(:account, :commodity_category, :service_category).page(params[:page]).per(params[:per_page] || Kaminari.config.default_per_page)

#     return [search, all_appointments]
#   end

#   def appointment_params
#     params.require(:register_form).permit(
#       :id, :account_id, :service_category_id, :commodity_category_id, :duplication, :company_name,
#       :company_tel, :company_url, :instagram_url, :content, :call_date, :next_call_date,
#       :sent_material_date, :is_next_call, :end_date
#     )
#   end

#   # private
# end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/index.html_20231110.erb
<h1>アポイントメント管理一覧</h1>
<% if false %>
  <%= form_with url: appointments_path, method: :get, local: true, id: 'service_category_form', data: { turbo_frame: 'appointment_list' } do |form| %>
    <%= form.label :service_category_type, "サービスタイプ: " %>
    <%= form.select :service_category_type,
                options_for_select([%w[SMM smm], %w[CX cx], %w[All all]], selected: params[:service_category_type]),
                { include_blank: "Please Select" },
                id: "service_category_select" %>
    <%= form.submit id: "test_submit", class: "apl-btn-blue", data: { turbo_frame: "appointment_list" } %>
  <% end %>

<% end %>


<%# #################### コメントアウトの代わり #################### %>
<% if false %>
  <%# ransackを利用した検索フォームでは、form_withの代わりにsearch_form_forを使う %>
  <div class="flex items-end mx-5">
  <%= search_form_for @search, html: { class: 'flex items-end' } do |f| %>
    <div class="flex flex-col mr-2">
      <%# `カラム名_cont`とすることで、カラムに対してLIKEを使った曖昧一致検索ができる %>
      <%= f.label :company_name_cont, "会社名(部分)" %>
      <%= f.search_field :company_name_cont %>
    </div>
    <div class="flex flex-col mr-2">
      <%# `カラム名_eq`とすることで、カラムに対して完全一致検索ができる %>
      <%= f.label :company_name_eq, "会社名(完全)" %>
      <%= f.search_field :company_name_eq %>
    </div>

    <div class="">
      <%# - 値を指定しないとransackがデフォルトで検索という文字列を使う %>
      <%= f.submit class: "apl-btn-blue", data: { turbo_frame: "appointment_list" } %>
      <%# 検索結果と検索フォームをクリアする %>
      <%= link_to "クリア", accounts_path, class: "apl-btn-reset" %>
    </div>
  <% end %>
  <%# - ransack用 検索機能 END %>Í
  <%= form_tag(request.path, method: :get, id: 'per_page_form') do %>
    Display:
    <%= select_tag "per_page", options_for_select([3, 5, 10, 20, 30, 50], params[:per_page].to_i), onchange: "this.form.submit()" %>
    items per page
    <%# ! 一時的に all で設定しているが、条件分岐が必要 %>
    <%= paginate @appointments, params: { per_page: params[:per_page] } %>
  <% end %>


<% end %>
<%# ####################  コメントアウト END  #################### %>


  <%# ¥¥¥ new 20231108 turboを使うには local: true 必須　¥¥¥ %>
  <%= form_with url: search_appointments_path, method: :get, local: true, html: { class: 'flex items-end' } do %>
    <div class="flex flex-col mr-2">
      <label for="company_name_partial">会社名(部分)</label>
      <input type="search" name="company_name_partial" id="company_name_partial">
    </div>
    <div class="flex flex-col mr-2">
      <label for="company_name_exact">会社名(完全)</label>
      <input type="search" name="company_name_exact" id="company_name_exact">
    </div>

    <div class="">
      <button type="submit" class="apl-btn-blue" data-turbo-frame="appointment_list">検索</button>
      <%= link_to "クリア", appointments_path, class: "apl-btn-reset" %>
    </div>
  <% end %>
  <%# ¥¥¥ new 20231108 ¥¥¥ %>


</div>
<%# - ransack用 END %>

<%= link_to :new_appointment, class: "apl-btn-green inline-block mx-5 my-2" do %>
  <!-- contents of the link go here -->
  <button class="">新規作成(normal)</button>
<% end %>
<%# ¥ 20231018 spi用のtrubo_frame使用している %>
<%# - 青木 要更新- 20231021 SPA %>
<%# ¥ 操作後変更したいもの - data: { turbo_frame: dom_id(ServiceCategory.new) } で操作後変更したい箇所を指定している %>

<%# #################### コメントアウトの代わり #################### %>

<%# <%= link_to "新規作成", :new_account, class: "apl-btn-green inline-block mx-5 my-2", data: { turbo_frame: dom_id("Account.new") } %>
<%# ! 条件分岐する予定 %>
<%= link_to "新規作成(使用可能)", new_appointment_path, class: "apl-btn-purple inline-block mx-5 my-2", data: { turbo_frame: "new_appointment" } %>

<%= turbo_frame_tag "appointment_list" do %>
  <%# marginが view-port内で効いてしまうため、ここにもmin-x-maxが必要!! %>
  <div class="m-5 border border-gray-200 rounded-lg shadow-md min-w-max">
    <%# !!!!!!!!!!!! %>
    <div class="text-sm border-t border-gray-100 divide-gray-100 min-w-max bg-whitetext-left text-gray-500divide-y">
      <%# ! min-w-max が必要!!!! %>
      <div class="flex bg-gray-50 min-w-max">
        <%# !!!!!!!!!!!!!!!!!!!11 %>
        <%# 1 edit + delete %>
        <div class="apl_project_common_header_col_style--w_two_icons">
          edit
        </div>

        <%# 2. :id (No.) %>
        <div class="apl_project_common_header_col_style--w_number_column">
          <%= sort_link(@search, :id, "No.", class: "text-blue-600 border-b border-blue-600") %>
        </div>

        <%# 3. :account_id %>
        <div class="apl_project_common_header_col_style--w_150px">
          <%= sort_link(@search, :account_id, t("activerecord.attributes.appointment.account_id"), class: "text-blue-600 border-b border-blue-600") %>
        </div>

        <%# 4. :service_category_id %>
        <div class="apl_project_common_header_col_style--w_150px">
          <%= sort_link(@search, :service_category_id, t("activerecord.attributes.appointment.service_category_id"), class: "text-blue-600 border-b border-blue-600") %>
        </div>

        <%# 5. :commodity_category_id %>
        <div class="apl_project_common_header_col_style--w_150px">
          <%= sort_link(@search, :commodity_category_id, t("activerecord.attributes.appointment.commodity_category_id"), class: "text-blue-600 border-b border-blue-600") %>
        </div>

        <%# 6. :duplication %>
        <div class="apl_project_common_header_col_style--w_150px">
          <%= sort_link(@search, :duplication, t("activerecord.attributes.appointment.duplication"), class: "text-blue-600 border-b border-blue-600") %>
        </div>

        <%# 7. :company_name %>
        <div class="apl_project_common_header_col_style--w_150px">
          <%= sort_link(@search, :company_name, t("activerecord.attributes.appointment.company_name"), class: "text-blue-600 border-b border-blue-600") %>
        </div>

        <%# 8. :company_tel %>
        <div class="apl_project_common_header_col_style--w_150px">
          <%= sort_link(@search, :company_tel, t("activerecord.attributes.appointment.company_tel"), class: "text-blue-600 border-b border-blue-600") %>
        </div>

        <%# 9. :company_url %>
        <div class="apl_project_common_header_col_style--w_150px">
          <%= sort_link(@search, :company_url, t("activerecord.attributes.appointment.company_url"), class: "text-blue-600 border-b border-blue-600") %>
        </div>

        <%# 10. :instagram_url %>
        <div class="apl_project_common_header_col_style--w_150px">
          <%= sort_link(@search, :instagram_url, t("activerecord.attributes.appointment.instagram_url"), class: "text-blue-600 border-b border-blue-600") %>
        </div>

        <%# 11. :content %>
        <div class="apl_project_common_header_col_style--w_600px">
          <%= sort_link(@search, :content, t("activerecord.attributes.appointment.content"), class: "text-blue-600 border-b border-blue-600") %>
        </div>

        <%# 12. :call_date %>
        <div class="apl_project_common_header_col_style--w_120px">
          <%= sort_link(@search, :call_date, t("activerecord.attributes.appointment.call_date"), class: "text-blue-600 border-b border-blue-600") %>
        </div>

        <%# 13. :next_call_date %>
        <div class="apl_project_common_header_col_style--w_120px">
          <%= sort_link(@search, :next_call_date, t("activerecord.attributes.appointment.next_call_date"), class: "text-blue-600 border-b border-blue-600") %>
        </div>

        <%# 14. :sent_material_date %>
        <div class="apl_project_common_header_col_style--w_120px">
          <%= sort_link(@search, :sent_material_date, t("activerecord.attributes.appointment.sent_material_date"), class: "text-blue-600 border-b border-blue-600") %>
        </div>

        <%# 15. :is_next_call %>
        <div class="apl_project_common_header_col_style--w_120px">
          <%= sort_link(@search, :is_next_call, t("activerecord.attributes.appointment.is_next_call"), class: "text-blue-600 border-b border-blue-600") %>
        </div>

        <%# 16. :end_date %>
        <div class="apl_project_common_header_col_style--w_120px">
          <%= sort_link(@search, :end_date, t("activerecord.attributes.appointment.end_date"), class: "text-blue-600 border-b border-blue-600") %>
        </div>

        <%# 17. edit + delete %>
        <div class="apl_project_common_header_col_style--w_two_icons">
          edit
        </div>

        <%# !!!!!!!!!!!!!!!!!!1 %>

      </div>
      <div id="accounts" class="border-t border-gray-100 divide-y divide-gray-100 min-w-max">
        <%= turbo_frame_tag "new_account_form" %>
        <%# ! 単一継承しているため、 一括で@appointments として取得してもCxAppointment と SmmAppointmentとそれぞれ認識されてしまうため下記は不可 %>
        <%# <%= render @appointments %>
        <%= render partial: "appointments/appointment", collection: @appointments %>
      </div>
    </div>
  </div>
  <%= paginate @appointments, params: { per_page: params[:per_page] } %>
<% end %>

<%# --------------- %>
<!-- component -->
<%# - 青木 要更新- 20231015 %>
<%# https://tinyurl.com/yst2dmtx %>

<%# ¥ ソート機能を自前で作成中 %>
<% sortable_columns = {
  id: ["No.", "col_width_number"],
  account_id: [t("activerecord.attributes.appointment.account_id"), "col_width_normal"],
  service_category_id: [t("activerecord.attributes.appointment.service_category_id"), "col_width_normal"],
  commodity_category_id: [t("activerecord.attributes.appointment.commodity_category_id"), "col_width_normal"],
  duplication: [t("activerecord.attributes.appointment.duplication"), "col_width_normal"],
  company_name: [t("activerecord.attributes.appointment.company_name"), "col_width_normal"],
  company_tel: [t("activerecord.attributes.appointment.company_tel"), "col_width_normal"],
  company_url: [t("activerecord.attributes.appointment.company_url"), "col_width_normal"],
  instagram_url: [t("activerecord.attributes.appointment.instagram_url"), "col_width_normal"],
  content: [t("activerecord.attributes.appointment.content"), "col_width_600px"],
  call_date: [t("activerecord.attributes.appointment.call_date"), "col_width_date"],
  next_call_date: [t("activerecord.attributes.appointment.next_call_date"), "col_width_date"],
  sent_material_date: [t("activerecord.attributes.appointment.sent_material_date"), "col_width_date"],
  is_next_call: [t("activerecord.attributes.appointment.is_next_call"), "col_width_number"],
  end_date: [t("activerecord.attributes.appointment.end_date"), "col_width_date"]
} %>

<%# 1 edit + delete: Static, no sorting %>
<div class="apl_project_common_header_col_style col_with_2_icons">
  edit
</div>

<%# Dynamic sorting links %>
<%# ¥ {sort: column, direction: sort_direction(column)}は、urlのparamとして渡される 20231108 %>
<% sortable_columns.each do |column, (title, width_class)| %>
  <div class="apl_project_common_header_col_style <%= width_class %>">
    <%= link_to title, { sort: column, direction: sort_direction(column) }, class: "text-blue-600 border-b border-blue-600" %>
  </div>
<% end %>

<%# 17 edit + delete: Static, no sorting %>
<div class="apl_project_common_header_col_style col_with_2_icons">
  edit
</div>