config/routes.rb
Rails.application.routes.draw do
  get "accounts/index"
  get "accounts/show"
  get "accounts/edit"
  get "accounts/new"
  get "accounts/create"
  get "accounts/update"
  get "accounts/destroy"
  get "commodity_categories/index"
  # root to: 'admin/top#index'
  root to: "top#index"

  # get "login" => "sessions#new", as: :login
  # post "session" => "sessions#create", as: :session
  # delete "session" => "sessions#destroy"

  # get 'login', to: 'sessions#new', as: :login
  # post 'session', to: 'sessions#create', as: :session
  # delete 'session', to: 'sessions#destroy'

  scope controller: :sessions do
    get "login", action: :new, as: :login
    # post 'session', action: :create, as: :session
    # delete 'session', action: :destroy
    # - 20231014 第一引数が urlにあたる
    resource :session, only: [:create, :destroy]
  end

  #^ 青木 ★要更新 - 20231014 /appointments/new => /apo/new  のように変更可能!
  resources :appointments, path: "appointments" do
    collection do
      get :search
    end
  end

  # ¥ 単一継承でも下記のように記載する必要あり
  resources :smm_appointments # This will generate smm_appointments_path among others
  resources :cx_appointments # This will generate cmm_appointments_path among others

  #^ 青木 ★要更新 - 20231014 /appointments/new => /apo/new  のように変更可能!
  resources :service_categories, path: "service_categories"

  resources :commodity_categories, path: "commodity_categories"

  resources :accounts, path: "accounts" do
    member do
      get "change_password", to: "accounts#change_password" # for displaying the password change form
      patch "update_password"  # for submitting the password change form
    end
  end

  # 検証用
  get "html/scroll_x"

  # # - 20231013 上記の書き換え 厳密には Prefix と URI-Patternが変わる
  # * Prefix: login => login_session   |   Uri-Pattern: /login  =>   /session/login
  # resource :session, only: [:new, :create, :destroy], controller: :sessions do
  #   get 'login', action: :new, as: :login
  # end

  # root "top#index"
  # get 'top/index', to: 'top#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  namespace :admin do
    root "top#index"
  end

  namespace :user do
    root "top#index"
  end
end

# - 20231013 - ルーティングに名前を与えるメリット:
# * シンボルでURLパスを表現することには、主に2つのメリットがあります。1つは、プログラマが名前を書き間違えたときにエラーになることです。たとえば、URLパスを文字列で指定した場合"/stuff/login" と書き間違えても、Railsはエラーを出しません。私たちが実際にリンクをクリックし「404 Not Found」のページを見て、はじめてミスに気づくことになります。しかし、URLパスにシンボル:stuff_login を指定した場合は、リンク元のページを表示しただけでエラーが発生します。間違いはなるべく早く発見されるべきですので、これは大きな利点です。

# ¥ 名前を与えることで login_path / login_url といったヘルパーメソッドが定義される
# ¥ => ヘルパーメソッドを用いるとurlにクエリパラメータを付与できる
# * 前者はURLのパス部分を返し、後者はURL全体を返します。　ヘルパーメソッド login_path を用いれば、次のようにしてERBテンプレートにリンクを埋め込むことができます。
# - <%= link_to "ログイン", login_path %>
# login_path の部分は:login とも書けるのでヘルパーメソッドの出番はなさそうにも思えますが、ヘルパーメソッドを用いるとURLにクエリパラメータを付加することが可能になります。
# - <%= link_to "ログイン", login_path(tracking: "001") %>
# この場合、次のようなHTMLコードが生成されます。
# - <a href="/login?tracking=001">ログイン</a>

app/models/account.rb
class Account < ApplicationRecord
  include StringNormalizer

  HUMAN_NAME_REGEXP = /\A[\p{han}\p{hiragana}\p{katakana}\u{30fc}A-Za-z]+\z/
  KATAKANA_REGEXP = /\A[\p{katakana}\u{30fc}]+\z/

  has_many :appointments

  attr_accessor :password, :password_confirmation
  # ¥ if @commodity_category.saveのタイミングで before_validationが起こる
  #  *  @commodity_category = CommodityCategory.new(commodity_categories_params)
  # * if @commodity_category.save
  before_validation do
    # * 引数の name は、現在のCommodityCategoryのインスタンスのname属性を指し、通常はデータベースのcommodity_categoriesテーブルのnameというカラムに対応する。
    # Store the original name before normalizing
    # self.original_name = name
    # Normalize the name
    self.name = normalize_as_name(name)
    self.name_kana = normalize_as_furigana(name_kana)
    self.email = normalize_as_email(email)
    # self.password = password
    # self.password_confirmation = password_confirmation

    # Normalize the name
    self.name = normalize_as_name(name)

    # ! # Normalize the 価格 rails7になったからか全角数字を半角に勝手に変更してくれている
    # self.price = normalize_zenkaku_number_to_number(price)
    # # Normalize the 初期費用
    # self.initial_cost = normalize_zenkaku_number_to_number(initial_cost)
  end

  # This callback hashes the password before saving (both create and update)
  before_save :hash_password_if_present

  # 余分な空白があった場合、取り除き、取り除いた旨のエラーメッセージを表示させる
  # validate_without_extra_spaces(:original_name, :name)

  # Validations
  # validates :password, presence: true, confirmation: true
  # validates :password_confirmation, presence: true

  # 必須
  validates :name, presence: true
  # ¥ ^ をつけると属性名を表示させないようにできる
  validates :name_kana, format: { with: KATAKANA_REGEXP, message: "はカタカナで入力してください", allow_blank: true }

  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :tel, format: { with: /\A\d+\z/, message: "は数字以外を含めないでください", allow_blank: true }

  # 文字制限 type text でない限り VARCHAR(255)
  validates_length_of :name, maximum: 255, message: "が長すぎます。255文字以内にしてください"

  # validates :password, presence: true, confirmation: true
  #- Validates password presence and confirmation only if it's present, mostly for updates.
  validates :password, presence: true, confirmation: true, if: :password_present?

  # # 正の整数限定 sqlの型が integer の場合の最大値は 2,147,483,647
  # # ! This validation declaration is evaluated in the class contextのため、format_with_delimiterは
  # # ! module ClassMethodsの中に記述する必要あり　 - クラスレベルで呼び出す必要があるため
  # validates :price, :initial_cost, numericality: {
  #   only_integer: true,
  #   greater_than_or_equal_to: 0,
  #   less_than_or_equal_to: INTEGER_MAX_VALUE, # Maximum value for a 4-byte signed integer
  #   message: "には#{format_with_delimiter(INTEGER_MAX_VALUE)}を上限とした正の整数を入力してください"
  # }

  # # - ransackを使用するため検索に使用する属性を定義する必要あり
  def self.ransackable_attributes(auth_object = nil)
    %w(id name name_kana gender email tel hashed_password employment_type description is_suspended is_admin)
  end

  def self.ransackable_associations(auth_object = nil)
    %w(appointments)
  end

  private

  # This method will be true if password is present, triggering the validation
  def password_present?
    !password.blank?
  end

  # Hashes the password using bcrypt
  def hash_password(password)
    puts("BCrypt::Password.create(password): #{BCrypt::Password.create(password)}")
    BCrypt::Password.create(password)
  end

  # Hashes the password if it's present, ensuring it's only done when needed
  def hash_password_if_present
    puts("hash_password(password) ::: #{hash_password(password)}")
    self.hashed_password = hash_password(password) if password_present?
  end
end

app/controllers/accounts_controller.rb
# class AccountsController < ApplicationController
# - turbo_frame or turbo_streamは使わない
class AccountsController < Base
  # skip_before_action :authorize

  def index
    # @accounts = Account.all
    # GET /service_categories
    # @service_categories = ServiceCategory.all
    # - service_categoriesに対してページネートできるようにする
    # @service_categories = ServiceCategory.page(params[:page])

    # `ServiceCategory.ransack`でServiceCategoryに対してransackを使う
    # params[:q]には検索フォームで指定した検索条件が入る
    @search = Account.ransack(params[:q])

    # デフォルトのソートをid降順にする
    @search.sorts = "id desc" if @search.sorts.empty?

    # `@search.result`で検索結果となる@service_categoriesを取得する
    # 検索結果に対してはkaminariのpageメソッドをチェーンできる
    @accounts = @search.result.page(params[:page]).per(params[:per_page] || Kaminari.config.default_per_page)
  end

  def show
  end

  def new
    @account_form = RegisterForm.new
    render action: "new"
  end

  def edit
    @account = Account.find(params[:id])
  end

  def update
    @account = Account.find(params[:id])
    if @account.update(account_update_params)
      flash[:notice] = "更新しました。"
      puts("flash[:success]: #{flash[:success]}")
      redirect_to action: :edit
    else
      puts @account.errors.full_messages
      flash[:alert] = "入力に誤りがあります。"
      # ! flashを出す出さないに関わらず、 status: は必須 ないと
      #! turbo.es2017-esm.js:2406 Error: Form responses must redirect to another location が発生する
      render "edit", status: :unprocessable_entity
    end
  end

  def create
    @account_form = RegisterForm.new(account_new_params)

    if @account_form.valid? # This will check validations without saving
      puts "Form is valid. Here are the parameters:"
      puts account_new_params.inspect # This will show what parameters are being passed to the form object
    else
      puts "Form is invalid. Here are the errors:"
      puts @account_form.errors.full_messages
    end

    # ¥ 20231012 app/services を使っている
    if @account_form.form_save
      if current_account
        flash[:notice] = "アカウントを新規作成しました。"
        # ! recirect_toすると turbo_streamによる flash表示はされない(別で設定してある通常のflashは動く)
        # ! => create.turbo_stream.erb 自体が動かない
        redirect_to new_account_path
      else
        flash[:notice] = "アカウントを新規作成しました。ログインしてください。"
        # ! recirect_toすると turbo_streamによる flash表示はされない(別で設定してある通常のflashは動く)
        # ! => create.turbo_stream.erb 自体が動かない
        redirect_to login_path
      end

      # ! redirect_to login_path をコメントアウトすると、 create.turbo_stream.erb が動き、
      # ! ページは現在のページのまま移動しない
    else
      flash.now[:alert] = "入力項目に誤りがあります。"
      puts("flash: #{flash.now[:alert]}")
      # ! render しないと バリデーションメッセージは表示されない!!
      render :new, status: :unprocessable_entity
    end
    puts("通常 create完了")
  end

  def destroy
    @account = Account.find(params[:id])
    if @account.destroy
      flash[:notice] = "Object was successfully deleted."
      # redirect_to objects_url
    else
      flash[:alert] = "Something went wrong"
      # redirect_to objects_url
    end
  end

  # ///////////////////////////////////////////////////////////////
  # * パスワード変更処理
  # ///////////////////////////////////////////////////////////////
  def change_password
    @account = Account.find(params[:id])
  end

  # PATCH /accounts/:id/update_password
  def update_password
    @account = Account.find(params[:id])
    # additional logic for authorization and security checks

    if @account.update(account_password_params)
      # handle a successful password change
      flash[:notice] = "パスワードを変更しました。"
      redirect_to root_path
    else
      flash.now[:alert] = "パスワードを変更できませんでした。"
      render :change_password
    end
  end

  private

  def account_new_params
    # - <input type="text" name="register_form[email]" id="register_form_email">
    params.require(:register_form).permit(:name, :name_kana, :email, :tel, :password, :description, :gender, :employment_type, :is_suspended, :is_admin, :password_confirmation)
  end

  # ¥ passwordはupdateしない
  def account_update_params
    # - <input type="text" name="register_form[email]" id="register_form_email">
    # params.require(:account).permit(:name, :name_kana, :email, :tel, :password, :description, :gender, :employment_type, :is_suspended, :is_admin, :password_confirmation)
    params.require(:account).permit(:name, :name_kana, :email, :tel, :description, :gender, :employment_type, :is_suspended, :is_admin)
  end

  # ¥ passwordの変更用
  def account_password_params
    # - <input type="text" name="register_form[email]" id="register_form_email">
    # params.require(:account).permit(:name, :name_kana, :email, :tel, :password, :description, :gender, :employment_type, :is_suspended, :is_admin, :password_confirmation)
    params.require(:account).permit(:password, :password_confirmation)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/change_password.html.erb
<%# ! 下記で画面全体に表示 - headerも隠れる %>
<%# <div class="flex items-center justify-center min-h-screen"> %>
<div class="flex items-center justify-center">
  <div class="w-full max-w-md p-6 bg-white rounded-lg shadow-lg">
    <div class="flex justify-center mb-8">
      <img src="https://www.emprenderconactitud.com/img/POC%20WCS%20(1).png" alt="Logo" class="h-20 w-30">
    </div>
    <h1 class="mt-8 mb-6 text-2xl font-semibold text-center text-gray-500">パスワードの変更</h1>

    <%# post create => accounts_path %>
    <%# ! Setting local: false ensures that the form submission is handled by Turbo. %>
    <%= form_with model: @account, url: update_password_account_path, local:true do |f| %>
      <%# - 青木 要削除 - 20231102 %>
      <% puts("@account.errors ::: #{@account.errors}") %>
      <% if @account.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@account.errors.count, "error") %>
            prohibited this account from being saved:</h2>

          <ul>
            <% @account.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% else %>
        <h2><%= pluralize(@account.errors.count, "error") %>
          No validation error messages?:</h2>
      <% end %>

      <%# * 新規作成の場合のみ、パスワード関係入力欄を標示する %>

      <%# ! password 確認 %>
      <div class="mb-4">
        <%= f.label :password, "新しいパスワード <span class='required-asterisk'>*</span>".html_safe, class: "block mb-2 text-sm text-gray-600" %>
        <%= f.password_field :password, class: "w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-cyan-500", required: true %>
        <%= render partial: "/shared/validation_errors", locals: { object: @account, attribute: :password } %>
      </div>

      <div class="mb-6">
        <%= f.label :password_confirmation, "新しいパスワード(確認) <span class='required-asterisk'>*</span>".html_safe, class: "block mb-2 text-sm text-gray-600" %>
        <%= f.password_field :password_confirmation, class: "w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-cyan-500", required: true %>
        <%= render partial: "/shared/validation_errors", locals: { object: @account, attribute: :password_confirmation } %>
      </div>
      <%# ! password 確認 %>

      <div class="flex justify-center mt-7">
        <%= f.submit @conditional_btn_txt,
                 class: "w-32 bg-gradient-to-r from-orange-400 to-orange-600 text-white py-2 rounded-lg block focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-cyan-500 mb-2 mr-6 cursor-pointer" %>

        <%= link_to "一覧",
        accounts_path,
        class: "text-center w-32 bg-gradient-to-r from-sky-400 to-sky-600 text-white py-2 rounded-lg block focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-cyan-500 mb-2" %>
      </div>

    <% end %>

    <%# #################### コメントアウトの代わり #################### %>
    <% if false %>
      <div class="mb-2 text-white cursor-pointer from-orange-400 to-orange-950 focus:ring-cyan-500 "></div>
    <% end %>
    <%# ####################  コメントアウト END  #################### %>

    <div class="text-center">
      <p class="text-sm">¿Ya tienes una cuenta?
        <a href="#" class="text-cyan-600">Inicia sesión</a></p>
    </div>
    <p class="mt-8 text-xs text-center text-gray-600">&copy; 2023 WCS LAT</p>
  </div>
</div>

app/views/accounts/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Accounts#create</h1>
  <p>Find me in app/views/accounts/create.html.erb</p>
</div>

app/views/accounts/create.turbo_stream.erb
<%# ¥ flashメッセージを notice か alertかを判断して turbo_streamで表示する %>

<% puts("アカウントaccounts  ^^  動いている??") %>
<%# アカウント作成時には ログイン画面にredirect する設定にしているため、実際は使わない  %>
<%= render "/shared/turbo_stream_flash" %>

<%
=begin
%>

<% if flash[:notice] %>
  <%= turbo_stream.update 'flash', partial: 'shared/flash_notice', locals: { msg: flash.notice } %>
<% end %>
<% if flash[:alert] %>
  <%= turbo_stream.update 'flash', partial: 'shared/flash_alert', locals: { msg: flash.alert } %>
<% end %>

<%
=end
%>

<%# - 動いた %>
<%
=begin
%>

<% if flash[:notice].present? %>
  <%= turbo_stream.update 'flash' do %>
    <div id="flash" class="alert alert-success">
      <%= flash[:notice] %>
    </div>
  <% end %>
<% end %>

<% if flash[:alert].present? %>
  <%= turbo_stream.update 'flash' do %>
    <div id="flash" class="alert alert-danger">
      <%= flash[:alert] %>
    </div>
  <% end %>
<% end %>

<%
=end
%>

app/views/accounts/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Accounts#destroy</h1>
  <p>Find me in app/views/accounts/destroy.html.erb</p>
</div>

app/views/accounts/destroy.turbo_stream.erb
<%# CommodityCategory詳細（`#commodity_category_1`となる要素）を削除する %>
<% puts("@account ::: #{@account}") %>
<%= turbo_stream.remove @account %>
<%# ¥ flashメッセージを notice か alertかを判断して turbo_streamで表示する %>
<%= render "/shared/turbo_stream_flash" %>

app/views/accounts/edit.html.erb
<div>
  <h1 class="text-4xl font-bold">Accounts#<%= action_name %></h1>
  <p>Find me in app/views/accounts/<%= action_name %>.html.erb</p>
</div>

<%# ¥ 下記変数を _form.html.erbに送る %>
<% @conditional_title = "アカウント編集" %>
<% @conditional_btn_txt = "変更" %>
<% @conditional_form_with_path = account_path(@account) %>
<% @model_or_form_object = @account %>
<% @background_color = "bg-green-100" %>

<%= render "form" %>

app/views/accounts/index.html.erb
<div>
  <h1 class="text-4xl font-bold">Accounts#index</h1>
  <p>Find me in app/views/accounts/index.html.erb</p>
  <%= link_to "新規作成", :new_account, class: "apl-btn-blue" %>
  <%# <button class="apl-btn-blue">新規作成</button> %>
</div>

<div>余裕があるときにアイコンをアップロードし、表示できるようにする</div>
<div><%= Account.find(1).name_kana %></div>

<%# - ransack用 検索機能 %>
<%# ransackを利用した検索フォームでは、form_withの代わりにsearch_form_forを使う %>
<div class="flex items-end mx-5">
  <%= search_form_for @search, html: { class: 'flex items-end' } do |f| %>
    <div class="flex flex-col mr-2">
      <%# `カラム名_cont`とすることで、カラムに対してLIKEを使った曖昧一致検索ができる %>
      <%= f.label :name_cont, "アカウント名(部分)" %>
      <%= f.search_field :name_cont %>
    </div>
    <div class="flex flex-col mr-2">
      <%# `カラム名_eq`とすることで、カラムに対して完全一致検索ができる %>
      <%= f.label :name_eq, "アカウント名(完全)" %>
      <%= f.search_field :name_eq %>
    </div>

    <div class="">
      <%# - 値を指定しないとransackがデフォルトで検索という文字列を使う %>
      <%= f.submit class: "apl-btn-blue", data: { turbo_frame: "account_list" } %>
      <%# 検索結果と検索フォームをクリアする %>
      <%= link_to "クリア", accounts_path, class: "apl-btn-reset" %>
    </div>
  <% end %>
  <%= form_tag(request.path, method: :get, id: 'per_page_form') do %>
    Display:
    <%= select_tag "per_page", options_for_select([3, 5, 10, 20, 30, 50], params[:per_page].to_i), onchange: "this.form.submit()" %>
    items per page
    <%= paginate @accounts, params: { per_page: params[:per_page] } %>
  <% end %>
</div>
<%# - ransack用 END %>

<%= link_to :new_account, class: "apl-btn-green inline-block mx-5 my-2" do %>
  <!-- contents of the link go here -->
  <button class="">新規作成(normal)</button>
<% end %>
<%# ¥ 20231018 spi用のtrubo_frame使用している %>
<%# - 青木 要更新- 20231021 SPA %>
<%# ¥ 操作後変更したいもの - data: { turbo_frame: dom_id(ServiceCategory.new) } で操作後変更したい箇所を指定している %>

<%# #################### コメントアウトの代わり #################### %>

<%# <%= link_to "新規作成", :new_account, class: "apl-btn-green inline-block mx-5 my-2", data: { turbo_frame: dom_id("Account.new") } %>
<%# ! 条件分岐する予定 %>
<%= link_to "新規作成(使用不可)", new_appointment_path, class: "apl-btn-purple inline-block mx-5 my-2", data: { turbo_frame: "new_appointment" } %>

<%= turbo_frame_tag "account_list" do %>
  <%# marginが view-port内で効いてしまうため、ここにもmin-x-maxが必要!! %>
  <div class="m-5 border border-gray-200 rounded-lg shadow-md min-w-max">
    <%# !!!!!!!!!!!! %>
    <div class="text-sm border-t border-gray-100 divide-gray-100 min-w-max bg-whitetext-left text-gray-500divide-y">
      <%# ! min-w-max が必要!!!! %>
      <div class="flex py-4 bg-gray-50 min-w-max">
        <%# !!!!!!!!!!!!!!!!!!!11 %>
        <%# 1 edit + delete %>
        <div class="apl_project_common_header_col_style--w_two_icons">
          edit
        </div>

        <%# 2 %>
        <div class="apl_project_common_header_col_style--w_number_column">
          <%= sort_link(@search, :id, "No.", class: "text-blue-600 border-b border-blue-600") %>
        </div>

        <%# 3 %>
        <div class="apl_project_common_header_col_style--w_300px">
          <%= sort_link(@search, :name, t("activerecord.attributes.account.name"), class: "text-blue-600 border-b border-blue-600") %>
        </div>

        <%# 4 %>
        <div class="apl_project_common_header_col_style--w_300px">
          <%= sort_link(@search, :name_kana, t("activerecord.attributes.account.name_kana"), class: "text-blue-600 border-b border-blue-600") %>
        </div>

        <%# 5 %>
        <div class="apl_project_common_header_col_style--w_300px">
          <%= sort_link(@search, :email, t("activerecord.attributes.account.email"), class: "text-blue-600 border-b border-blue-600") %>
        </div>

        <%# 6 %>
        <div class="apl_project_common_header_col_style--w_300px">
          <%= sort_link(@search, :tel, t("activerecord.attributes.account.tel"), class: "text-blue-600 border-b border-blue-600") %>
        </div>

        <%# 7 %>
        <div class="apl_project_common_header_col_style--w_600px">
          <%= sort_link(@search, :description, t("activerecord.attributes.account.description"), class: "text-blue-600 border-b border-blue-600") %>
        </div>

        <%# 8 %>
        <div class="apl_project_common_header_col_style--w_300px">
          <%= sort_link(@search, :gender, t("activerecord.attributes.account.gender"), class: "text-blue-600 border-b border-blue-600") %>
        </div>

        <%# 9 %>
        <div class="apl_project_common_header_col_style--w_300px">
          <%= sort_link(@search, :employment_type, t("activerecord.attributes.account.employment_type"), class: "text-blue-600 border-b border-blue-600") %>
        </div>

        <%# 10 %>
        <div class="apl_project_common_header_col_style--w_300px">
          <%= sort_link(@search, :is_suspended, t("activerecord.attributes.account.is_suspended"), class: "text-blue-600 border-b border-blue-600") %>
        </div>

        <%# 11 %>
        <div class="apl_project_common_header_col_style--w_300px">
          <%= sort_link(@search, :is_admin, t("activerecord.attributes.account.is_admin"), class: "text-blue-600 border-b border-blue-600") %>
        </div>

        <%# 12 %>
        <div class="apl_project_common_header_col_style--w_two_icons">
          edit
        </div>

        <%# !!!!!!!!!!!!!!!!!!1 %>

      </div>
      <div id="accounts" class="border-t border-gray-100 divide-y divide-gray-100 min-w-max">
        <%= turbo_frame_tag "new_account_form" %>
        <%= render @accounts %>
      </div>
    </div>
  </div>
  <%= paginate @accounts, params: { per_page: params[:per_page] } %>
<% end %>

<%# ####################  コメントアウト END  #################### %>

<%# --------------- %>
<!-- component -->
<%# - 青木 要更新- 20231015 %>
<%# https://tinyurl.com/yst2dmtx %>

app/views/accounts/new.html.erb
<%# ! scssのみ使用する %>
<%= stylesheet_link_tag "account", media: "all", "data-turbolinks-track": "reload" %>
<div>
  <h1 class="text-4xl font-bold">Accounts#new</h1>
  <p>Find me in app/views/accounts/new.html.erb</p>
</div>

<%# ¥ 下記変数を _form.html.erbに送る %>
<% @conditional_title = "アカウント登録" %>
<% @conditional_btn_txt = "登録" %>
<% @conditional_form_with_path = accounts_path %>
<%# form_with model: にわたすオブジェクト %>
<% @model_or_form_object = @account_form %>
<% @background_color = "bg-white" %>

<%= render "form" %>

app/views/accounts/show.html.erb
<div>
  <h1 class="font-bold text-4xl">Accounts#show</h1>
  <p>Find me in app/views/accounts/show.html.erb</p>
</div>

app/views/accounts/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Accounts#update</h1>
  <p>Find me in app/views/accounts/update.html.erb</p>
</div>